version: '3.3'
services:
  dev:
    image: 151345152001.dkr.ecr.ap-northeast-2.amazonaws.com/popo-public-web:latest
    ports:
     - 5000:3000
    logging:
      driver: local
      options:
        max-size: 10m
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      placement:
        constraints:
         - node.role != manager
         - node.labels.application == popo
  prod:
    # Prod Image Tag should be updated manually
    image: 151345152001.dkr.ecr.ap-northeast-2.amazonaws.com/popo-public-web:release-x.x.x
    ports:
     - 3000:3000
    logging:
      driver: local
      options:
        max-size: 10m
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      placement:
        constraints:
         - node.role != manager
         - node.labels.application == popo
