on:
  push:
    tags: ["*"]

name: Docker Build and Push

env:
  ECR_REGISTRY: 151345152001.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: popo-public-web

jobs:
  docker-build-and-push:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64' # support AWS EC2 t4g
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Determine Prod/Dev Stage
        run: |
          if [[ ${{ github.ref }} == refs/tags/release-* ]]; then
            echo "PROD"
            echo "IMAGE_TAG=prod" >> $GITHUB_ENV
          else
            echo "DEV"
            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
          fi
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64 # support AWS EC2 t4g
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
